apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dolibarr

resources:
  - namespace.yaml
  - secret.yaml
  - mysql.yaml
  - dolibarr.yaml
  - service.yaml

# ✅ Replace deprecated 'commonLabels' with 'labels'
labels:
  - pairs:
      managed-by: argocd
      environment: dev
    includeSelectors: false
    includeTemplates: false
