apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: dolibarr
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_DATABASE: dolibarr
  MYSQL_USER: dolibarr
  MYSQL_PASSWORD: dolipass
