apiVersion: v1
kind: Service
metadata:
  name: dolibarr
  namespace: dolibarr
  labels:
    app: dolibarr
spec:
  type: NodePort
  selector:
    app: dolibarr
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
      name: dolibarr-http
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: dolibarr
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
