apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 01-falco-helm-application.yaml
  - 03-falco-rules-config.yaml
  - 04-falco-event-forwarder.yaml
  - 05-webhook-service.yaml
# 02-falco-helm-values.yaml is referenced by the Argo CD Application
# and not applied directly via kustomize
