apiVersion: v1
kind: Service
metadata:
  name: odoo-nodeport
  namespace: odoo
spec:
  type: NodePort
  selector:
    app: odoo
  ports:
    - port: 8069
      targetPort: 8069
      nodePort: 30069
      name: odoo

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: odoo
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
