apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-velero
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.4.0
    helm:
      valuesObject:
        rootUser: minioadmin
        rootPassword: minioadmin123

        persistence:
          enabled: true
          size: 50Gi

        service:
          type: NodePort
          port: 9000
          nodePort: 30900

        consoleService:
          type: NodePort
          port: 9001
          nodePort: 30901

        buckets:
          - name: velero-backups
            policy: none
            purge: false
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
