apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: "6.2.0"
    chart: velero
    helm:
      values: |
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.9.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins

        credentials:
          useSecret: true
          secretContents:
            cloud: |
              [default]
              aws_access_key_id = AKIAXFTRPC2CYBO7H5PH
              aws_secret_access_key = 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

        configuration:
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: velero-backups
              config:
                region: minio
                s3ForcePathStyle: "true"
                s3Url: "http://minio.velero.svc:9000"
              default: true
          volumeSnapshotLocation:
            - name: default
              provider: aws
              config:
                region: minio

        deployNodeAgent: false
        metrics:
          enabled: false

        serviceAccount:
          server:
            create: true
            name: velero

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

        rbac:
          create: true

  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
