apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    chart: velero
    targetRevision: 8.2.0
    helm:
      valuesObject:
        credentials:
          useSecret: true
          secretContents:
            cloud: |
              [default]
              aws_access_key_id=minioadmin
              aws_secret_access_key=minioadmin123

        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.10.0
            volumeMounts:
              - mountPath: /target
                name: plugins

        configuration:
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: velero-backups
              default: true
              config:
                region: minio
                s3ForcePathStyle: "true"
                s3Url: http://minio.velero.svc.cluster.local:9000

          volumeSnapshotLocation: []

        snapshotsEnabled: false
        deployNodeAgent: true

        schedules:
          daily-critical:
            disabled: false
            schedule: "0 3 * * *"
            template:
              includedNamespaces:
                - argocd
                - monitoring
                - wordpress
                - velero
              ttl: 720h0m0s

          weekly-full:
            disabled: false
            schedule: "0 2 * * 0"
            template:
              includedNamespaces:
                - "*"
              ttl: 168h0m0s
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
