apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/planb438/git-ops.git
    targetRevision: main
    path: minio-velero-gitops
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true